apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: streaming-server-pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
