---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-server-deployment
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: streaming-server
  template:
    metadata:
      labels:
        app: streaming-server
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: streaming-server-config
          image: codeworksio/streaming-server:latest
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 15
          name: streaming-server
          ports:
            - containerPort: 1935
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - mountPath: /data
              name: storage
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "100m"
              memory: "256Mi"
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: streaming-server-pvc