apiVersion: v1
kind: Service
metadata:
  name: streaming-server-service
  labels:
    name: streaming-server-service
    namespace: dev
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30000
    - name: rtmp
      port: 1935
      targetPort: 1935
      nodePort: 30001
  selector:
    name: streaming-server
    namespace: dev